# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://gnever.github.io
date_format: "ordinal"
title: 随记
subtitle: "this is gao"
description: "郜"
keywords:gao 
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author:xubin gao 
organization: Gee.
organization_url: https://www.hiwi.com
location: Beijing, China
email: gaobin32643@126.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于
# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: gnever.github.io

# ---------------- #
#      Socials     #
# ---------------- #
github_username: gnever

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, duoshuo
#comments_provider: disqus
# !!!重要!!! 请修改下面两个用户名为你自己申请的
# !!!Important!!! Please modify usernames below to yours
#duoshuo_username: 
#disqus_username: 
# 在使用 disqus 的时候可点击显示多说评论框
#lazy_load_duoshuo: true

# ---------------- #
#    Analytics     #
# ---------------- #
#google:
#    analytics_id: 

# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [php, JavaScript, Nginx]
